services:
  - type: web
    name: moviemate
    env: python
    plan: free
    region: oregon
    pythonVersion: 3.10.13
    buildCommand: ./fetch_data.sh && pip install -r requirements.txt
    startCommand: uvicorn src.api_server:app --host 0.0.0.0 --port $PORT

